development:
  adapter: postgresql
  encoding: unicode
  database: goplango_development
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: goplango_test
  pool: 5
  username: kellywaters
  password: 